package com.example.maxfitvipgymapp.Model;

import org.json.JSONException;
import org.json.JSONObject;

public class Member {
    private int id;
    private String code;
    private String membershipId;
    private String firstName;
    private String lastName;
    private String phoneNumber;
    private String createdDate;
    private String lastActive;
    private boolean isDeleted;
    private int platformId;
    private boolean isActive;

    public Member() {}

    public Member(JSONObject json) throws JSONException {
        this.id = json.optInt("id", 0);
        this.code = json.optString("code", "");
        this.membershipId = json.optString("membership_id", "");
        this.firstName = json.optString("first_name", "");
        this.lastName = json.optString("last_name", "");
        this.phoneNumber = json.optString("phone_number", "");
        this.createdDate = json.optString("created_date", "");
        this.lastActive = json.optString("last_active", "");
        this.isDeleted = json.optBoolean("is_deleted", false);
        this.platformId = json.optInt("platform_id", 0);
        this.isActive = json.optBoolean("is_active", false);
    }

    public JSONObject toJSON() throws JSONException {
        JSONObject json = new JSONObject();

        // ✅ Include 'code' if it's set (for creation with pre-generated code)
        if (code != null && !code.isEmpty()) {
            json.put("code", code);
        }

        // NOTE: 'id' is still excluded as it's auto-generated by database

        if (membershipId != null && !membershipId.isEmpty()) {
            json.put("membership_id", membershipId);
        }
        if (firstName != null && !firstName.isEmpty()) {
            json.put("first_name", firstName);
        }
        if (lastName != null && !lastName.isEmpty()) {
            json.put("last_name", lastName);
        }
        if (phoneNumber != null && !phoneNumber.isEmpty()) {
            json.put("phone_number", phoneNumber);
        }

        // Always include these fields
        json.put("platform_id", platformId);
        json.put("is_active", isActive);
        json.put("is_deleted", false); // Always false for new members

        return json;
    }

    // Getters and Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getCode() { return code; }
    public void setCode(String code) { this.code = code; }

    public String getMembershipId() { return membershipId; }
    public void setMembershipId(String membershipId) { this.membershipId = membershipId; }

    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }

    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }

    public String getPhoneNumber() { return phoneNumber; }
    public void setPhoneNumber(String phoneNumber) { this.phoneNumber = phoneNumber; }

    public String getCreatedDate() { return createdDate; }
    public void setCreatedDate(String createdDate) { this.createdDate = createdDate; }

    public String getLastActive() { return lastActive; }
    public void setLastActive(String lastActive) { this.lastActive = lastActive; }

    public boolean isDeleted() { return isDeleted; }
    public void setDeleted(boolean deleted) { isDeleted = deleted; }

    public int getPlatformId() { return platformId; }
    public void setPlatformId(int platformId) { this.platformId = platformId; }

    public boolean isActive() { return isActive; }
    public void setActive(boolean active) { isActive = active; }

    public String getFullName() {
        return firstName + " " + lastName;
    }
}